diversity:
  database:
    host-and-port: localhost:5432
  images:
    directory: ./e2e/images
  contact:
    email: contact@mnhn.com
    subject: Message du portail diversité
  security:
    secret-key: 'tw/Nir/A8vY0yz4rU1Ea3KFzGTW5S6IrEkFLPYDf32E='

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css


spring:
  datasource:
    url: jdbc:postgresql:diversity
    username: diversity
    password: diversity
  flyway:
    enabled: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths:
            - '/*.js'
            - '/*.css'
      cache: true
      compressed: true
    cache:
      cachecontrol:
        max-age: '365d'
  mail:
    host: localhost
  mvc:
    locale: fr_FR
    locale-resolver: fixed
  servlet:
    multipart:
      max-file-size: 5MB

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://${diversity.database.host-and-port}/diversity_test
    username: diversity
    password: diversity

---
spring:
  profiles: e2e
  datasource:
    url: jdbc:postgresql://${diversity.database.host-and-port}/diversity_e2e
    username: diversity
    password: diversity
server:
  port: 8081
diversity:
  images:
    directory: ./e2e/images

---
spring:
  profiles:
    dev
  resources:
    static-locations:
      - classpath:/static/
      - file:./frontend/build/dist/
    chain:
      cache: false

---
spring:
  profiles:
    ci
  mail:
    host: mailhog
    port: 1025
diversity:
  database:
    host-and-port: postgres:5432
