diversity:
  database:
    host-and-port: localhost:5432
  images:
    directory: ./images
  contact:
    email: contact@mnhn.com
    subject: Message du portail diversité
  security:
    secret-key: 'tw/Nir/A8vY0yz4rU1Ea3KFzGTW5S6IrEkFLPYDf32E='
  matomo:
    host: ''
    site-id: ''

server:
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/javascript
      - text/html
      - text/css
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:postgresql:diversity
    username: diversity
    password: diversity
  flyway:
    enabled: true
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths:
              - '/*.js'
              - '/*.css'
        cache: true
        compressed: true
      cache:
        cachecontrol:
          max-age: '365d'
    locale: fr_FR
    locale-resolver: fixed
  mail:
    host: localhost
  servlet:
    multipart:
      max-file-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://${diversity.database.host-and-port}/diversity_test
    username: diversity
    password: diversity

---
spring:
  config:
    activate:
      on-profile: e2e
  datasource:
    url: jdbc:postgresql://${diversity.database.host-and-port}/diversity_e2e
    username: diversity
    password: diversity
server:
  port: 8081
diversity:
  images:
    directory: ./e2e/images

---
spring:
  config:
    activate:
      on-profile: dev
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./frontend/build/dist/
      chain:
        cache: false

---
spring:
  config:
    activate:
      on-profile: ci
  mail:
    host: mailhog
    port: 1025
diversity:
  database:
    host-and-port: postgres:5432
